propose:
  description: >
    You are proposing the motion: {motion}
    Come up with a clear arguments in favour of the motion
    Be very convincing.
  expected_output: >
    Your clear argument in favour of the motion in a concise manner
  agent: debator
  output_file: output/propose.md

oppose:
  description: >
    You are in opposition of the motion: {motion}
    Come up with a clear arguments against the motion
    Be very convincing.
  expected_output: >
    Your clear argument against the motion, in a concise manner.
  agent: debator
  output_file: output/oppose.md

decide:
  description: >
    Review the arguments presented by the debators and decide which side is more convincing
  expected_output: >
    You decide which side is more convincing, and why
  agent: judge
  output_file: output/decide.md
